# Generated by Django 5.0.14 on 2026-03-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeBaselineLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(help_text="e.g., 'Long Rains 2025' or 'Season 1 – March 2025'", max_length=100)),
                ('test_date', models.DateField(help_text='Date the KALRO lab sample was taken (not the date results were received)')),
                ('nitrogen_mg_per_kg', models.FloatField(help_text='Total Nitrogen (N) in mg/kg from KALRO report')),
                ('phosphorus_mg_per_kg', models.FloatField(help_text='Total Phosphorus (P) in mg/kg from KALRO report')),
                ('potassium_mg_per_kg', models.FloatField(help_text='Total Potassium (K) in mg/kg from KALRO report')),
                ('ph_at_test_date', models.FloatField(help_text='Soil pH measured by KALRO lab (cross-calibration reference)')),
                ('ec_us_per_cm_at_test_date', models.FloatField(help_text='Electrical Conductivity in µS/cm from KALRO lab')),
                ('organic_carbon_percent', models.FloatField(blank=True, help_text='Organic Carbon % — if included in KALRO report (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE active baseline per field at a time. When a new baseline is entered, the previous one is auto-deactivated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_tests', to='farms.field')),
            ],
            options={
                'verbose_name': 'KALRO Composite Baseline Lab Test',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='NPKPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_nitrogen_mg_per_kg', models.FloatField()),
                ('predicted_phosphorus_mg_per_kg', models.FloatField()),
                ('predicted_potassium_mg_per_kg', models.FloatField()),
                ('confidence_score', models.FloatField(blank=True, help_text='Model R² score (0–1). Surfaced in mobile app.', null=True)),
                ('model_version', models.CharField(default='v1.0', help_text='Tracks which ML model version produced this prediction', max_length=50)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_used', models.ForeignKey(help_text='Which KALRO baseline anchor this prediction was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomics.compositebaselinelabtest')),
                ('telemetry_reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npk_prediction', to='telemetry.dailyiottelemetry')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='AgronomicRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('LIME_APPLICATION', 'Apply Agricultural Lime (pH Correction)'), ('CAN_TOP_DRESS', 'Apply CAN Top-Dressing (Nitrogen Boost)'), ('DAP_BASAL', 'Apply DAP Basal (Phosphorus Correction)'), ('MANURE_BASAL', 'Apply Farmyard Manure (Organic Basal)'), ('IRRIGATE', 'Activate Irrigation Pump'), ('NO_ACTION', 'No Intervention Required')], max_length=30)),
                ('message', models.TextField(help_text="e.g., 'Apply 50 kg CAN per acre. Soil N critically low at 12 mg/kg.'")),
                ('quantity_kg_per_acre', models.FloatField(blank=True, help_text='Calculated input quantity in kg per acre (null for irrigation triggers)', null=True)),
                ('forecast_rain_24h_mm', models.FloatField(blank=True, help_text='Open-Meteo forecasted rainfall used in this decision (mm)', null=True)),
                ('relay_triggered', models.BooleanField(default=False, help_text='True if a HIGH signal was sent to the ESP32 relay GPIO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('npk_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='agronomics.npkprediction')),
            ],
            options={
                'verbose_name': 'Agronomic Recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
