# Generated by Django 5.0.14 on 2026-03-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomics', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agronomicrecommendation',
            name='forecast_rain_24h_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agronomicrecommendation',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agronomicrecommendation',
            name='quantity_kg_per_acre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agronomicrecommendation',
            name='relay_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='ec_us_per_cm_at_test_date',
            field=models.FloatField(help_text='EC in µS/cm from KALRO lab'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only ONE active baseline per field at a time.'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='nitrogen_mg_per_kg',
            field=models.FloatField(help_text='Total N in mg/kg from KALRO report'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='organic_carbon_percent',
            field=models.FloatField(blank=True, help_text='Organic Carbon % (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='ph_at_test_date',
            field=models.FloatField(help_text='Soil pH from KALRO lab'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='phosphorus_mg_per_kg',
            field=models.FloatField(help_text='Total P in mg/kg from KALRO report'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='potassium_mg_per_kg',
            field=models.FloatField(help_text='Total K in mg/kg from KALRO report'),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='season_label',
            field=models.CharField(help_text="e.g., 'Long Rains 2025'", max_length=100),
        ),
        migrations.AlterField(
            model_name='compositebaselinelabtest',
            name='test_date',
            field=models.DateField(help_text='Date the KALRO lab sample was taken'),
        ),
        migrations.AlterField(
            model_name='npkprediction',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Model R² score (0–1)', null=True),
        ),
        migrations.AlterField(
            model_name='npkprediction',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='npkprediction',
            name='telemetry_reading',
            field=models.OneToOneField(db_constraint=False, help_text='TimescaleDB does not support FK constraints on hypertables. Enforced in application layer.', on_delete=django.db.models.deletion.CASCADE, related_name='npk_prediction', to='telemetry.dailyiottelemetry'),
        ),
    ]
