# Generated by Django 5.0.14 on 2026-03-27 10:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Safaricom/Airtel number for SMS alerts (e.g., +254712345678)', max_length=20)),
                ('location_county', models.CharField(blank=True, help_text='e.g., Kiambu, Nyandarua, Nakuru', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable farm name, e.g., 'Gatundu Upper Plot'", max_length=200)),
                ('centroid_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('centroid_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farms.farmer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'North Block' or 'Section A'", max_length=200)),
                ('fodder_type', models.CharField(choices=[('napier', 'Napier Grass (Pennisetum purpureum)'), ('rhodes', 'Rhodes Grass (Chloris gayana)'), ('mixed', 'Mixed Fodder'), ('other', 'Other')], default='napier', help_text='Primary crop grown — determines KALRO threshold values in the rules engine', max_length=20)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='GeoJSON polygon drawn by farmer in the mobile app', null=True, srid=4326)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated area in hectares (auto-populated on save)', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
            options={
                'ordering': ['farm', 'name'],
            },
        ),
    ]
