# Generated by Django 5.0.14 on 2026-03-27 10:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIoTTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='WGS84 GPS coordinates from NEO-6M. geography=True for metre-accurate IDW.', srid=4326)),
                ('device_id', models.CharField(db_index=True, help_text='ESP32 device MAC address or provisioned UUID', max_length=64)),
                ('moisture_percent', models.FloatField(help_text='Volumetric Water Content (VWC) in % (0–100)')),
                ('temperature_celsius', models.FloatField(help_text='Soil temperature in °C at probe depth')),
                ('ph', models.FloatField(help_text='Soil pH (0–14 scale)')),
                ('ec_raw_us_per_cm', models.FloatField(help_text='Raw Electrical Conductivity in µS/cm (NOT temperature-compensated)')),
                ('ec_25_us_per_cm', models.FloatField(blank=True, help_text='Temperature-compensated EC at 25°C. Formula: EC₂₅ = EC_raw / (1 + 0.019 × (T − 25)). Null until the async Celery worker processes this reading.', null=True)),
                ('delta_ec_from_baseline', models.FloatField(blank=True, help_text='EC₂₅ minus the KALRO baseline EC. Tracks ion depletion over time.', null=True)),
                ('hmac_signature', models.CharField(help_text='HMAC-SHA256 hex digest received from ESP32 (for audit)', max_length=64)),
                ('battery_voltage', models.FloatField(blank=True, help_text='ESP32 battery voltage in V (from ADC pin) — for low-battery alerts', null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Set to True by Celery worker after EC₂₅, ML inference, and rules engine complete')),
                ('field', models.ForeignKey(blank=True, help_text='Auto-populated by Celery worker via PostGIS point-in-polygon query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_readings', to='farms.field')),
            ],
            options={
                'verbose_name': 'IoT Telemetry Reading',
                'verbose_name_plural': 'IoT Telemetry Readings',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['device_id', '-time'], name='idx_device_time'), models.Index(fields=['is_processed', '-time'], name='idx_unprocessed')],
            },
        ),
    ]
